minVersion: 2.21.1
statusProvider:
  name: github
artifactProvider:
  name: github
targets:
  - name: github
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
requireNames:
  - /^scm-.+-py3-none-any\.whl$/